# Items
items = [
{ :name =>"Antimatter Charge S", :id => "222" },
{ :name =>"Carbonized Lead M", :id => "186" },
{ :name =>"EMP M", :id => "193" },
{ :name =>"Fusion M", :id => "191" },
{ :name =>"Inferno Cruise Missile", :id => "204" },
{ :name =>"Inferno Heavy Assault Missile", :id => "20308" },
{ :name =>"Inferno Heavy Missile", :id => "208" },
{ :name =>"Inferno Light Missile", :id => "211" },
{ :name =>"Lead Charge M", :id => "226" },
{ :name =>"Lead Charge S", :id => "218" },
{ :name =>"Microwave S", :id => "240" },
{ :name =>"Mjolnir Cruise Missile", :id => "202" },
{ :name =>"Mjolnir Heavy Assault Missile", :id => "20306" },
{ :name =>"Mjolnir Heavy Missile", :id => "207" },
{ :name =>"Nova Cruise Missile", :id => "205" },
{ :name =>"Nova Heavy Assault Missile", :id => "21867" },
{ :name =>"Nuclear S", :id => "179" },
{ :name =>"Phased Plasma M", :id => "192" },
{ :name =>"Radio L", :id => "255" },
{ :name =>"Radio M", :id => "247" },
{ :name =>"Scourge Cruise Missile", :id => "203" },
{ :name =>"Scourge Heavy Assault Missile", :id => "20307" },
{ :name =>"Scourge Heavy Missile", :id => "209" },
{ :name =>"Scourge Light Missile", :id => "210" },
{ :name =>"Standard L", :id => "258" },
{ :name =>"Standard M", :id => "250" },
{ :name =>"Xray L", :id => "260" },
{ :name =>"Xray M", :id => "252" },
{ :name =>"Xray S", :id => "244" },
{ :name =>"Acolyte I", :id => "2203" },
{ :name =>"Hammerhead I", :id => "2183" },
{ :name =>"Hobgoblin I", :id => "2454" },
{ :name =>"Hornet I", :id => "2464" },
{ :name =>"Warrior I", :id => "2486" },
{ :name =>"Cap Booster 50", :id => "264" },
{ :name =>"Giant Secure Container", :id => "11489" },
{ :name =>"Station Container", :id => "17366" },
{ :name =>"100mm Reinforced Steel Plates I", :id => "11293" },
{ :name =>"10MN Afterburner I", :id => "12056" },
{ :name =>"10MN Microwarpdrive I", :id => "12052" },
{ :name =>"125mm Gatling AutoCannon I", :id => "484" },
{ :name =>"150mm Railgun I", :id => "565" },
{ :name =>"1MN Afterburner I", :id => "439" },
{ :name =>"1MN Microwarpdrive I", :id => "434" },
{ :name =>"200mm AutoCannon I", :id => "486" },
{ :name =>"200mm Reinforced Steel Plates I", :id => "11295" },
{ :name =>"250mm Railgun I", :id => "570" },
{ :name =>"400mm Reinforced Steel Plates I", :id => "11297" },
{ :name =>"425mm AutoCannon I", :id => "491" },
{ :name =>"50mm Reinforced Steel Plates I", :id => "11291" },
{ :name =>"Adaptive Invulnerability Field I", :id => "578" },
{ :name =>"Adaptive Nano Plating I", :id => "1304" },
{ :name =>"Cap Recharger I", :id => "1195" },
{ :name =>"Co-Processor I", :id => "3887" },
{ :name =>"Damage Control I", :id => "2046" },
{ :name =>"ECM - Multispectral Jammer I", :id => "1957" },
{ :name =>"ECM - Phase Inverter", :id => "1958" },
{ :name =>"ECM - White Noise Generator I", :id => "1956" },
{ :name =>"Energized Adaptive Nano Membrane I", :id => "11267" },
{ :name =>"Energized Armor Layering Membrane I", :id => "11237" },
{ :name =>"Expanded Cargohold I", :id => "1317" },
{ :name =>"Focused Medium Pulse Laser I", :id => "456" },
{ :name =>"Heavy Assault Missile Launcher I", :id => "20138" },
{ :name =>"Heavy Beam Laser I", :id => "459" },
{ :name =>"Heavy Missile Launcher I", :id => "501" },
{ :name =>"Heavy Neutron Blaster I", :id => "568" },
{ :name =>"Large Ancillary Shield Booster", :id => "4391" },
{ :name =>"Large Micro Jump Drive", :id => "4383" },
{ :name =>"Light Ion Blaster I", :id => "563" },
{ :name =>"Light Missile Launcher I", :id => "499" },
{ :name =>"Medium Ancillary Armor Repairer", :id => "33101" },
{ :name =>"Medium Ancillary Shield Booster", :id => "32772" },
{ :name =>"Medium Armor Repairer I", :id => "3528" },
{ :name =>"Medium Shield Booster I", :id => "10836" },
{ :name =>"Medium Shield Extender I", :id => "3829" },
{ :name =>"Mega Beam Laser I", :id => "463" },
{ :name =>"Mega Pulse Laser I", :id => "462" },
{ :name =>"Miner I", :id => "483" },
{ :name =>"Mining Laser Upgrade", :id => "22542" },
{ :name =>"Reactive Armor Hardener", :id => "4403" },
{ :name =>"Shield Recharger I", :id => "393" },
{ :name =>"Small Armor Repairer I", :id => "523" },
{ :name =>"Small Capacitor Booster I", :id => "3566" },
{ :name =>"Small Focused Beam Laser I", :id => "454" },
{ :name =>"Small Focused Pulse Laser I", :id => "453" },
{ :name =>"Small Hull Repairer I", :id => "524" },
{ :name =>"Small Shield Booster I", :id => "399" },
{ :name =>"Small Shield Extender I", :id => "377" },
{ :name =>"Small Tractor Beam I", :id => "24348" },
{ :name =>"Stasis Webifier I", :id => "26" },
{ :name =>"Survey Scanner I", :id => "444" },
{ :name =>"Target Spectrum Breaker", :id => "4409" },
{ :name =>"Tracking Computer I", :id => "1977" },
{ :name =>"Tracking Disruptor I", :id => "2108" },
{ :name =>"Warp Disruptor I", :id => "3242" },
{ :name =>"Warp Scrambler I", :id => "447" },
{ :name =>"X-Large Ancillary Shield Booster", :id => "32780" },
{ :name =>"Algos", :id => "32872" },
{ :name =>"Amarr Shuttle", :id => "11134" },
{ :name =>"Ashimmu", :id => "17922" },
{ :name =>"Corax", :id => "32876" },
{ :name =>"Crucifier", :id => "2161" },
{ :name =>"Dragoon", :id => "32874" },
{ :name =>"Imicus", :id => "607" },
{ :name =>"Iteron Mark V", :id => "657" },
{ :name =>"Magnate", :id => "29248" },
{ :name =>"Moa", :id => "623" },
{ :name =>"Nereus", :id => "650" },
{ :name =>"Punisher", :id => "597" },
{ :name =>"Rupture", :id => "629" },
{ :name =>"Venture", :id => "32880" },
{ :name =>"Vexor", :id => "626" }
]
puts "Confirming Items In DB"
items.each do |itm|
	Item.create( :typeid => itm[:id], :name => itm[:name]);
end
